[settings]
timeout = 1000

[relaychain]
chain = "rococo-local"
default_command = "./bin/polkadot"

  [[relaychain.nodes]]
  name = "alice"
  validator = true
  ws_port = 9900
  extra_args = [ "-lparachain=debug" ]

  [[relaychain.nodes]]
  name = "bob"
  validator = true
  extra_args = [ "-lparachain=debug" ]

[[parachains]]
id = 1005
add_to_genesis = false
chain = "coretime-rococo-local"

  [[parachains.collators]]
  name = "coretime-collator01"
  command = "./bin/polkadot-parachain"
  ws_port = 9910
  args = ["--log=xcm=trace"]

  [[parachains.collators]]
  name = "coretime-collator02"
  command = "./bin/polkadot-parachain"
  ws_port = 9911
  args = ["--log=xcm=trace"]

[[parachains]]
id = 2000
addToGenesis = false

  [parachains.collator]
  name = "regionx-collator01"
  command = "./bin/regionx-node"
  ws_port = 9920
  args = [ "--log=xcm=trace,regions=trace,ismp=trace" ]
